[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid

[program:nginx]
command=/bin/sh -c '/usr/sbin/nginx -g "daemon off;" 2>&1 | sed -u "s/^/[nginx] /"'
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:puma]
command=/bin/sh -c 'stdbuf -oL -eL bundle exec puma -b tcp://0.0.0.0:8000 config.ru 2>&1 | sed -u "s/^/[puma] /"'
directory=/app
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
